/**
 * Menu JSON untuk sidebar CBT
 * Setiap menu: icon, title, url, allowed_role, hidden, badge_text, badge_type, dan optional submenu
 */

const sidebarMenu = [
	{
		icon: "home",
		title: "Beranda",
		url: "/dashboard",
		allowed_role: ["admin", "guru", "siswa"],
		hidden: false,
		badge_text: null,
		badge_type: null,
		submenu: [
			{
				icon: "chart-bar",
				title: "Statistik",
				url: "/statistik",
				allowed_role: ["admin", "guru"],
				hidden: false,
			},
			{
				icon: "trophy",
				title: "Leaderboard",
				url: "/leaderboard",
				allowed_role: ["admin", "guru", "siswa"],
				hidden: false,
			},
			{
				icon: "bullhorn",
				title: "Pengumuman",
				url: "/pengumuman",
				allowed_role: ["admin", "guru", "siswa"],
				hidden: false,
			},
			{
				icon: "calendar",
				title: "Kalender",
				url: "/kalender",
				allowed_role: ["admin", "guru", "siswa"],
				hidden: false,
			},
			{
				icon: "newspaper",
				title: "Berita",
				url: "/berita",
				allowed_role: ["admin", "guru", "siswa"],
				hidden: false,
			},
			{
				icon: "bell",
				title: "Notifikasi",
				url: "/notifikasi",
				allowed_role: ["admin", "guru", "siswa"],
				hidden: false,
				badge_text: "3",
				badge_type: "error",
			},
			{
				icon: "envelope",
				title: "Pesan",
				url: "/pesan",
				allowed_role: ["admin", "guru", "siswa"],
				hidden: false,
			},
		],
	},
	{
		icon: "book-open",
		title: "Data Modul",
		url: "/modul",
		allowed_role: ["admin", "guru"],
		hidden: false,
		submenu: [
			{
				icon: "layers",
				title: "Modul/Topik",
				url: "/modul",
				allowed_role: ["admin", "guru"],
				hidden: false,
			},
			{
				icon: "file-alt",
				title: "Paket Soal",
				url: "/paket-soal",
				allowed_role: ["admin", "guru"],
				hidden: false,
			},
			{
				icon: "upload",
				title: "Import Soal",
				url: "/import-soal",
				allowed_role: ["admin", "guru"],
				hidden: false,
			},
			{
				icon: "list",
				title: "Daftar Soal",
				url: "/daftar-soal",
				allowed_role: ["admin", "guru"],
				hidden: false,
			},
			{
				icon: "folder-open",
				title: "File Manager",
				url: "/file-manager",
				allowed_role: ["admin", "guru"],
				hidden: false,
			},
		],
	},
	{
		icon: "users",
		title: "Data Peserta",
		url: "/peserta",
		allowed_role: ["admin", "guru"],
		hidden: false,
		submenu: [
			{
				icon: "user",
				title: "Peserta",
				url: "/peserta",
				allowed_role: ["admin", "guru"],
				hidden: false,
			},
			{
				icon: "users-cog",
				title: "Kelas & Kelompok",
				url: "/kelas",
				allowed_role: ["admin", "guru"],
				hidden: false,
			},
			{
				icon: "user-plus",
				title: "Import Peserta",
				url: "/import-peserta",
				allowed_role: ["admin", "guru"],
				hidden: false,
			},
			{
				icon: "id-card",
				title: "Cetak Kartu",
				url: "/cetak-kartu",
				allowed_role: ["admin", "guru"],
				hidden: false,
			},
		],
	},
	{
		icon: "clipboard-list",
		title: "Data Ujian",
		url: "/ujian",
		allowed_role: ["admin", "guru"],
		hidden: false,
		submenu: [
			{
				icon: "calendar-check",
				title: "Jadwal Ujian",
				url: "/jadwal-ujian",
				allowed_role: ["admin", "guru"],
				hidden: false,
			},
			{
				icon: "file-signature",
				title: "Data Ujian",
				url: "/data-ujian",
				allowed_role: ["admin", "guru"],
				hidden: false,
			},
			{
				icon: "check-double",
				title: "Evaluasi Ujian",
				url: "/evaluasi-ujian",
				allowed_role: ["admin", "guru"],
				hidden: false,
			},
			{
				icon: "award",
				title: "Hasil Ujian",
				url: "/hasil-ujian",
				allowed_role: ["admin", "guru"],
				hidden: false,
			},
			{
				icon: "chart-pie",
				title: "Rekap Hasil Ujian",
				url: "/rekap-hasil-ujian",
				allowed_role: ["admin", "guru"],
				hidden: false,
			},
			{
				icon: "cogs",
				title: "Pengaturan Ujian",
				url: "/pengaturan-ujian",
				allowed_role: ["admin", "guru"],
				hidden: false,
			},
			{
				icon: "key",
				title: "Token Ujian",
				url: "/token-ujian",
				allowed_role: ["admin", "guru"],
				hidden: false,
			},
		],
	},
	{
		icon: "hammer",
		title: "Alat",
		url: "/alat",
		allowed_role: ["admin"],
		hidden: false,
		submenu: [
			{
				icon: "database",
				title: "Database",
				url: "/database",
				allowed_role: ["admin"],
				hidden: false,
			},
			{
				icon: "save",
				title: "Backup & Restore",
				url: "/backup-restore",
				allowed_role: ["admin"],
				hidden: false,
			},
		],
	},
	{
		icon: "user-circle",
		title: "Kelola Akun",
		url: "/akun",
		allowed_role: ["admin"],
		hidden: false,
		submenu: [
			{
				icon: "role",
				title: "Peran (Role)",
				url: "/role",
				allowed_role: ["admin"],
				hidden: false,
			},
			{
				icon: "user",
				title: "Akun",
				url: "/account",
				allowed_role: ["admin"],
				hidden: false,
			},
		],
	},
	{
		icon: "settings",
		title: "Pengaturan",
		url: "/pengaturan",
		allowed_role: ["admin"],
		hidden: false,
		submenu: [
			{
				icon: "server",
				title: "Sistem & Server",
				url: "/sistem-server",
				allowed_role: ["admin"],
				hidden: false,
			},
			{
				icon: "app-store",
				title: "Aplikasi",
				url: "/aplikasi",
				allowed_role: ["admin"],
				hidden: false,
			},
			{
				icon: "shield-alt",
				title: "Keamanan",
				url: "/keamanan",
				allowed_role: ["admin"],
				hidden: false,
			},
			{
				icon: "plug",
				title: "Integrasi",
				url: "/integrasi",
				allowed_role: ["admin"],
				hidden: false,
			},
			{
				icon: "question-circle",
				title: "Bantuan",
				url: "/bantuan",
				allowed_role: ["admin"],
				hidden: false,
			},
			{
				icon: "info-circle",
				title: "Tentang",
				url: "/tentang",
				allowed_role: ["admin"],
				hidden: false,
			},
			{
				icon: "book",
				title: "Dokumentasi",
				url: "/dokumentasi",
				allowed_role: ["admin"],
				hidden: false,
			},
			{
				icon: "address-book",
				title: "Kontak",
				url: "/kontak",
				allowed_role: ["admin"],
				hidden: false,
			},
			{
				icon: "file-contract",
				title: "Kebijakan Privasi",
				url: "/kebijakan-privasi",
				allowed_role: ["admin"],
				hidden: false,
			},
			{
				icon: "file-signature",
				title: "Syarat & Ketentuan",
				url: "/syarat-ketentuan",
				allowed_role: ["admin"],
				hidden: false,
			},
			{
				icon: "code-branch",
				title: "Versi",
				url: "/versi",
				allowed_role: ["admin"],
				hidden: false,
				badge_text: "v1.0",
				badge_type: "info",
			},
			{
				icon: "history",
				title: "Log Perubahan",
				url: "/log-perubahan",
				allowed_role: ["admin"],
				hidden: false,
			},
			{
				icon: "comment-dots",
				title: "Umpan Balik",
				url: "/umpan-balik",
				allowed_role: ["admin"],
				hidden: false,
			},
		],
	},
];


export default sidebarMenu;